# Generated by Django 4.0.1 on 2022-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=35)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidade', models.IntegerField()),
                ('publicador', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos_photos')),
            ],
        ),
    ]
